# Generated by Django 3.2.12 on 2022-02-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rollNum', models.CharField(max_length=10)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('dob', models.DateField(null=True)),
            ],
        ),
    ]
