# Generated by Django 3.2.12 on 2022-02-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('Lname', models.CharField(max_length=20)),
                ('rollNum', models.CharField(max_length=10)),
                ('dob', models.DateField(null=True)),
                ('Gender', models.DateField(null=True)),
                ('Mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
