# Generated by Django 4.1.4 on 2022-12-09 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_laptop_delete_mainform_delete_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='model',
            new_name='Model',
        ),
        migrations.AlterModelTable(
            name='laptop',
            table='laptop_demo',
        ),
    ]
