# Generated by Django 4.1.4 on 2022-12-09 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_rename_model_laptop_model_alter_laptop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptop',
            table='demo_laptop',
        ),
    ]
