# Generated by Django 4.1.4 on 2022-12-09 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_alter_laptop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='laptop',
            table='demo_laptoppp',
        ),
    ]
