# Generated by Django 4.1.4 on 2023-02-10 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_repair_delete_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=20)),
                ('Message', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'demo_messages',
            },
        ),
    ]
