# Generated by Django 4.1.4 on 2023-02-10 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='message',
        ),
    ]
