# Generated by Django 4.1.4 on 2023-02-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_rename_message_suggestion_alter_repair_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='suggestion',
            table='demo_suggestions',
        ),
    ]
